refactor: use esm modules (broken)
currently failing with Exception while evaluating JS: (new TypeError("undefined is not a non-null object", "<stdin>", 1))
  @<stdin>:1:990
  @<stdin>:1:1035

Error: failed to initialize JS

Caused by:
    0: the `wizer.initialize` function trapped
    1: Exited with i32 exit status 1
       wasm backtrace:
           0: 0x3c517e - <unknown>!<wasm function 8451>
           1: 0x3c5ae0 - <unknown>!<wasm function 8464>
           2: 0x13a80 - <unknown>!<wasm function 212>
           3: 0x13618 - <unknown>!<wasm function 210>
           4: 0x13c64 - <unknown>!<wasm function 214>
       note: run with `WASMTIME_BACKTRACE_DETAILS=1` environment variable to display more information`